### ISSUE TITLE
Minuit objective function to accept other parameters without trying to fit them

### ISSUE THREAD

**Issue by TSA26** [jpivarski/pyminuit#41]
Is it possible to send other parameters(that might be needed for calculation but they are already known) in objective function without Minuit trying to fit them to?
Best explained through example:

```
def cost_function(x, y, z, a):
return (x - 2) ** 2 + (y - 3) ** 2 + (z - 4) ** 2
cost_function.errordef = Minuit.LEAST_SQUARES

m = Minuit(cost_function, x=0, y=0, z=0, a=6)

m.migrad()  # run optimiser
print(m.values)  # x: 2, y: 3, z: 4, a:6
```

I don't want Minuit to find value for a, because I already have it, but I need a in objective function

**Comment by jpivarski** [comment]
First thing: you should switch to iminuit—I haven't been thinking about pyminuit since maybe 2010 or so. iminuit is in active development.

Your question is more general than that, though. One way to get quantities into a function is just by having them in the surrounding scope—a function defined inside another function will see the outer function's variables. Minuit won't even know about those variables, but you can set and reset them from outside the minimization process.

Another way is to pass them as arguments but make them "fixed" arguments. Minuit will be aware of those arguments, printing them out if "printlevel" is non-zero and setting their values however you initialize them, but they won't be varied in the search for a minimum. "Fixed" is an extreme form of "limits," which constrains how far an argument is allowed to vary.

**Comment by TSA26** [comment]
Actually, I am using iminuit, just didn't realized my post is in wrong git.
I am currently doing it in a way you first suggested it, but I thought it would be convenient if I could just send other arguments to objective function.
Anyway, I tried with a fixed parameter like you suggested, and it is working.
Thank you very much.
